export const chamberCards = [
  { name:'Goblin With a Clipboard', kind:'threat', strength:2, loot:1, renown:1, consequence:'Lose 1 Renown. Bureaucracy wins again.', art:'📋', text:'A tiny administrator demands tribute in triplicate.' },
  { name:'Basement Slime Choir', kind:'threat', strength:3, loot:1, renown:1, consequence:'Discard 1 random card.', art:'🎶', text:'Gross. Harmonized. Somehow confident.' },
  { name:'Rusty Hallway Knight', kind:'threat', strength:4, loot:1, renown:1, consequence:'Unequip one Gear if possible.', art:'🛡️', text:'His armor squeaks louder than his threats.' },
  { name:'Mimic Ottoman', kind:'threat', strength:5, loot:2, renown:1, consequence:'Discard 1 Loot card from hand.', art:'🪑', text:'It looks comfy. It is not.' },
  { name:'Tax Dragon Intern', kind:'threat', strength:6, loot:2, renown:1, consequence:'Lose 1 Renown and discard 1 card.', art:'🐉', text:'Still learning to audit, already learning to burn.' },
  { name:'Skeleton Influencer', kind:'threat', strength:7, loot:2, renown:1, consequence:'All rivals draw 1 Loot.', art:'💀', text:'Like, comment, subscribe, perish.' },
  { name:'Bridge Troll in HR', kind:'threat', strength:8, loot:2, renown:1, consequence:'Skip your next Scavenge option.', art:'🌉', text:'Needs you to complete onboarding before crossing.' },
  { name:'Possessed Vending Machine', kind:'threat', strength:9, loot:3, renown:1, consequence:'Discard your highest bonus Gear.', art:'🥤', text:'It eats coins, dreams, and kneecaps.' },
  { name:'Three Kobolds in a Robe', kind:'threat', strength:10, loot:3, renown:1, consequence:'Lose 2 Renown, minimum 1.', art:'🧥', text:'A legal adult monster, technically.' },
  { name:'Ancient Spreadsheet Lich', kind:'threat', strength:12, loot:3, renown:2, consequence:'Discard 2 random cards.', art:'📊', text:'It has formulas older than kingdoms.' },
  { name:'Parking Lot Minotaur', kind:'threat', strength:13, loot:3, renown:2, consequence:'Lose all temporary combat boosts.', art:'🐂', text:'You are not leaving without validating.' },
  { name:'The Snack Hydra', kind:'threat', strength:15, loot:4, renown:2, consequence:'Each rival steals 1 random card from you if possible.', art:'🐍', text:'Every head wants a different chip.' },
  { name:'Doom Roomba', kind:'threat', strength:16, loot:4, renown:2, consequence:'Unequip one Gear and lose 1 Renown.', art:'🧹', text:'Tiny wheels. Massive grievance.' },
  { name:'The Finalized Boss Baby', kind:'threat', strength:18, loot:5, renown:2, consequence:'Reset to 1 Renown if you fail escape.', art:'👶', text:'Do not negotiate with toddlers in capes.' },
  { name:'Hex: Pocket Sand Prophecy', kind:'hex', art:'🌀', text:'The current player loses 1 Renown, minimum 1.', effect:{ type:'loseRenown', amount:1 } },
  { name:'Hex: Sudden Inventory Audit', kind:'hex', art:'🧾', text:'The current player discards a random card.', effect:{ type:'discardRandom', amount:1 } },
  { name:'Hex: Boots Full of Soup', kind:'hex', art:'🥣', text:'The current player has -2 in their next combat.', effect:{ type:'nextCombatPenalty', amount:2 } },
  { name:'Hex: Cursed Group Chat', kind:'hex', art:'📱', text:'Every rival draws 1 Chamber card face-down.', effect:{ type:'rivalsDrawChamber', amount:1 } },
  { name:'Hex: Dramatic Stair Failure', kind:'hex', art:'🪜', text:'The current player must roll escape at -1 this turn.', effect:{ type:'escapePenalty', amount:1 } },
  { name:'Role: Brute', kind:'role', art:'💪', text:'+2 power while you fight alone.', role:'Brute' },
  { name:'Role: Sneak', kind:'role', art:'🗡️', text:'+1 escape roll. Once per turn, you may brag about it.', role:'Sneak' },
  { name:'Role: Hexer', kind:'role', art:'🔮', text:'+2 when playing Boosts against a Threat.', role:'Hexer' },
  { name:'Role: Tinker', kind:'role', art:'🔧', text:'+1 power for each equipped Gear after the first two.', role:'Tinker' },
  { name:'Origin: Stoneborn', kind:'origin', art:'🪨', text:'+1 power. Too stubborn to be moved.', origin:'Stoneborn' },
  { name:'Origin: Skyfolk', kind:'origin', art:'🪽', text:'+1 to escape rolls.', origin:'Skyfolk' },
  { name:'Origin: Nightkin', kind:'origin', art:'🌙', text:'Your first Sabotage each combat gets +1.', origin:'Nightkin' },
  { name:'Origin: Wildblood', kind:'origin', art:'🔥', text:'+2 power when you are losing combat by 3 or more.', origin:'Wildblood' },
  { name:'Empty Chamber with Bad Vibes', kind:'found', art:'🚪', text:'Nothing attacks. Somehow worse.' },
  { name:'Mysterious Side Closet', kind:'found', art:'🗝️', text:'Keep this. You may Scavenge an extra Loot on a later turn.', effect:{ type:'sideCloset' } },
  { name:'Suspiciously Helpful Statue', kind:'found', art:'🗿', text:'Gain +1 temporary power in your next combat.', effect:{ type:'nextCombatBonus', amount:1 } }
];

export const lootCards = [
  { name:'Foam Sword of Confidence', kind:'gear', slot:'hand', bonus:1, value:200, art:'🗡️', text:'+1 power. Looks fake. Hits emotionally.' },
  { name:'Boots of Leaving Early', kind:'gear', slot:'feet', bonus:1, escape:1, value:300, art:'🥾', text:'+1 power and +1 escape.' },
  { name:'Helmet of Questionable Authority', kind:'gear', slot:'head', bonus:2, value:400, art:'⛑️', text:'+2 power if you say it with confidence.' },
  { name:'Cardboard Breastplate', kind:'gear', slot:'body', bonus:2, value:350, art:'📦', text:'+2 power. Rain voids warranty.' },
  { name:'Two-Handed Apology Axe', kind:'gear', slot:'twohand', bonus:4, value:700, art:'🪓', text:'+4 power. Takes both hands and one apology.' },
  { name:'Tiny Crown of Main Character Energy', kind:'gear', slot:'head', bonus:3, value:800, art:'👑', text:'+3 power. Absolutely unbearable.' },
  { name:'Snack Belt', kind:'gear', slot:'trinket', bonus:1, value:300, art:'🍫', text:'+1 power. Emergency cheese included.' },
  { name:'Ring of Barely Legal Loopholes', kind:'gear', slot:'trinket', bonus:2, value:600, art:'💍', text:'+2 power. The rules hate it.' },
  { name:'Left Shoe of Destiny', kind:'gear', slot:'feet', bonus:2, value:450, art:'👟', text:'+2 power. The right one is missing.' },
  { name:'Intern Wand', kind:'gear', slot:'hand', bonus:2, value:500, art:'🪄', text:'+2 power. It mostly opens PDFs.' },
  { name:'Emergency Energy Drink', kind:'boost', side:'hero', amount:3, art:'⚡', text:'Play during combat: +3 to the hero side.' },
  { name:'Suspicious Coupon', kind:'boost', side:'hero', amount:2, art:'🎟️', text:'Play during combat: +2 to the hero side.' },
  { name:'Theme Park Turkey Leg', kind:'boost', side:'hero', amount:4, art:'🍗', text:'Play during combat: +4 to the hero side. Powerful and greasy.' },
  { name:'Dramatic Slow Walk', kind:'boost', side:'hero', amount:5, art:'🚶', text:'Play during combat: +5 to the hero side.' },
  { name:'Mildly Inspiring Playlist', kind:'boost', side:'hero', amount:2, art:'🎧', text:'Play during combat: +2 to the hero side.' },
  { name:'Actually Good Plan', kind:'boost', side:'hero', amount:6, art:'🧠', text:'Play during combat: +6 to the hero side. Rare.' },
  { name:'Enemy Gets a Second Wind', kind:'boost', side:'threat', amount:3, art:'🌬️', text:'Sabotage: +3 to the Threat.' },
  { name:'Justin-Level Nonsense', kind:'boost', side:'threat', amount:5, art:'😈', text:'Sabotage: +5 to the Threat. Annoying but effective.' },
  { name:'Scott Makes It Worse', kind:'boost', side:'threat', amount:4, art:'🧨', text:'Sabotage: +4 to the Threat.' },
  { name:'Sudden Floor Grease', kind:'boost', side:'threat', amount:2, art:'🧈', text:'Sabotage: +2 to the Threat and emotional damage.' },
  { name:'Loot: Mystery Sack', kind:'instant', art:'🎒', text:'Play on your turn: draw 2 Loot, then discard 1 random card.', effect:{ type:'drawLootDiscard', draw:2, discard:1 } },
  { name:'Loot: Vibe Check Passed', kind:'instant', art:'✅', text:'Gain 1 Renown, but cannot win with this card.', effect:{ type:'gainRenownNonWinning', amount:1 } },
  { name:'Loot: Insurance Fraud Goblin', kind:'instant', art:'🧌', text:'Steal 1 random card from a rival.', effect:{ type:'stealRandom' } },
  { name:'Loot: Pocket Portal', kind:'instant', art:'🌀', text:'End a losing combat and escape automatically.', effect:{ type:'autoEscape' } },
  { name:'Loot: Decorative Shield', kind:'gear', slot:'hand', bonus:1, value:250, art:'🛡️', text:'+1 power. Mostly vibes.' },
  { name:'Loot: Manager Keys', kind:'gear', slot:'trinket', bonus:3, value:900, art:'🔑', text:'+3 power. Opens something. Maybe.' },
  { name:'Loot: Haunted Hoodie', kind:'gear', slot:'body', bonus:3, value:750, art:'🧥', text:'+3 power. Extremely comfortable ghost.' },
  { name:'Loot: Coupon Sword', kind:'gear', slot:'hand', bonus:3, value:650, art:'⚔️', text:'+3 power. Expires at midnight.' },
  { name:'Loot: Problematic Wand', kind:'gear', slot:'hand', bonus:4, value:900, art:'🪄', text:'+4 power. HR wants a word.' },
  { name:'Loot: Bag of Holding Grudges', kind:'gear', slot:'trinket', bonus:2, value:550, art:'👜', text:'+2 power. Contains every argument.' }
];
